### PR TITLE
add windows executable, refered to activate.bat

### PR DESCRIPTION
**Pull request by liudonghua123**
Try to add a windows script, fix https://github.com/jeffbuttars/cowpy/issues/10.

### CODE REVIEW

**Comment by jeffbuttars** [comment]
Thanks!
I'll give this a test and merge it.

**Comment by liudonghua123** [comment]
@jeffbuttars, Hi, I don't quite understand what you mentioned, could you provide some more explainations or examples.

**Comment by jeffbuttars** [comment]
Yeah, I want to test it some more. I was using gitbash and I think I need to go back and try in the `cmd` shell and powershell.
I don't use Windows much and I'm new to using and developing Python on that platform. So I apologize for the delays on this.

The issue was, in gitbash, cowpy always listens to stdin for input instead of using a positional argument for the say text when stdin is not being used. It's a problem with Python's `isatty()` function not working the same on Windows and Linux.

```sh
# This works
echo "a message" | cowpy

# This hangs waiting for input on stdin
cowpy "a message" 
```

**Comment by liudonghua123** [comment]
@jeffbuttars , I don't have such problem, it's really strange.

image

**Comment by jeffbuttars** [comment]
I've gone back and tried it in cmd.exe and powershell and everything works for me as you've shown!
For whatever reason the GitBash CLI has stdin issues.

Thanks again for the PR.

**Pull request merged**
